### ISSUE TITLE
example gives warning

### ISSUE THREAD

**Issue by pdbailey0** [tmatta/lsasim#48] opened 2023-03-23 23:28 UTC
Hi,

I ran your example in `item_sim` and it gave an odd warning. This is from the version 2.1.2

```
item_gen(b_bounds = c(-2, 2), a_bounds = c(.75, 1.25),
thresholds = c(1, 2, 3), n_1pl = c(5, 5, 5), n_2pl = c(0, 0, 5))
# Warning message:
# In rbind(c(0, 0, 0), c(0, 0, 0), c(0, 0, 0), c(0, 0, 0), c(0, 0,  :
#   number of columns of result is not a multiple of vector length (arg 6)
```

**Comment by wleoncio** [comment] 2023-03-24 05:27
Hi Paul,

Thank you for reporting. I can confirm the issue, will investigate and get back to you soon.

**Comment by wleoncio** [comment] 2023-03-24 08:22
So the issue itself looks easy to explain: near the end of the function, `item_gen()` tries to use `rbind()` on vectors of different sizes. This seems to happen whenever the `thresholds` argument contains a vector of values that are not a multiple of one another. For example, `thresholds = c(1, 3)` and `c(2, 4, 8)` would work because of how R recycles vectors, whereas `c(2, 4, 6)` (and the `c(1, 2, 3)` from the example) won't.

I'm not familiar with the idea of thresholds in this context, but I expected the `d*` columns in the output should equal the number of thresholds for that particular item (filling with 0.00 for the missing thresholds). Consider the example below:

```r
item_gen(b_bounds = c(-1, 1), thresholds = c(1, 2, 4), n_1pl = c(1, 1, 1))
```

Depending on RNGesus' will, your result should be something like:

```
  item     b    d1    d2    d3   d4 a c k p
1    1 -0.46  0.00  0.00  0.00 0.00 1 0 1 1
2    2  0.07 -0.14  0.14 -0.14 0.14 1 0 2 1
3    3  0.66 -0.59 -0.01  0.17 0.43 1 0 4 1
```

Two things I don't understand:

1. Why does item 1 has d1 = d2 = 0? If that item has 1 threshold, shouldn't it have a non-zero value for d1?
2. Item 2 has d1 = d3 and d2 = d4 due to vector recycling. Shouldn't it have 4 different threshold values?

The fix could be as simple as padding the vectors with zeros and generating extra d-values where needed. I would like to get some confirmation that that's the correct solution before proceeding, though.

**Comment by mollyolaf** [comment] 2023-03-27 11:51
Hi Waldir!

What is the error? Otherwise, the first item won't have thresholds (d_j =
0) since just 1 is specified and that is captured in b.

Leslie

**Comment by wleoncio** [comment] 2023-03-27 12:58
Hi Leslie,

The error message only presents itself if `item_gen()` is asked to generate items with different numbers of thresholds that are not multiples of each other. So if I understood correctly, in the example above:

1. Item 1 should not have any threshold values (which is correct)
2. Item 3 should have 4 unique threshold values (which is also correct)

What about item 2? Shouldn't it only have values for d1 and d2?

**Comment by mollyolaf** [comment] 2023-03-27 15:45
Yes, all correct. And item 2 should have values for only d1 and d2. Not
sure if you noticed, but they are in fact repeats for d3 and d4: -0.14 0.14
-0.14 0.14.

So, looks like for whatever reason, the generating process is just
recycling thresholds even though there should be just 2 of them. The "k"
specification is even correct for item 2 where k=2.

Leslie

**Comment by wleoncio** [comment] 2023-03-28 04:11
Thank you for the clarification, @mollyolaf! :)

I noticed the vector recycling, the explanation for the behavior is in [my comment above](https://github.com/tmatta/lsasim/issues/48#issuecomment-1482421752), hope it's clear enough.

This week got a bit rushed with another package I'm trying to get into CRAN before I leave for vacation on Friday, but I think I can also find time to fix this. Worst case, I'll tacke it right after Easter break. :)

**Comment by wleoncio** [comment] 2023-03-28 09:51
Good news: got some free time here and pushed a solution. Technically, we just pad the missing threshold values with zeros so the matrix is complete (while also preventing R from recycling values). See code [here](https://github.com/tmatta/lsasim/commit/c2347afcef2cda3fbd86f180b97ade24697e2c2c#diff-2abfb004e55ddcc864b464a7599a0cbd473b0b15c48a479ac629d108f6817a16R144-R148) for more details.

Now I'm working on some unrelated fixes (it's no longer recommended to use `class()` inside if-statements); as soon as this is done, I'll submit the fix to CRAN.

**Comment by wleoncio** [comment] 2023-03-28 11:11
So lsasim version 2.1.3 containing the fix to this issue is on its way to CRAN, so I'll close this as resolved. Thanks again for your contribution, please let me know if the issue persists.

**Closed as completed by wleoncio** 2023-03-28 11:11 UTC
Labels: bug, help wanted
